### ISSUE TITLE
Update list to be numbered list, not bulleted list

### ISSUE THREAD

**Issue by emilyrohrbough** [LeoDog896/npm-rank#3]
Its hard to see where a package tracks if not in the top 5 as there are 1000 packages in the list. 😄

**Comment by tristan-f-r** [comment]
Thanks! I feel a bit silly for not doing this in the first place. I'll change that in a bit.

**Comment by tristan-f-r** [comment]
Fixed in https://github.com/LeoDog896/npm-rank/commit/265aa13669d2c9b61b92bdfc5e866f36fed99af5

**Comment by emilyrohrbough** [comment]
thank you!! 🙏🏻
