### ISSUE TITLE
Less than 10000 npm packages

### ISSUE THREAD

**Issue by weddige** [LeoDog896/npm-rank#4]
The list (at least the [raw data](https://github.com/LeoDog896/npm-rank/releases/download/latest/raw.txt)) contains less than 10000 entries. Right now there are 9997 entries.

**Comment by tristan-f-r** [comment]
Thanks! I'll look into it, and add a test case on the CI to ensure this doesn't happen again.

**Comment by tristan-f-r** [comment]
All fixed! Tell me if the problem reappears.
